
many_command:
many_command:
many_command:
	echo "many times!"
hello:
	echo "world!" && sleep 1
	echo "wat!"
empty_command:


many_command:
subcommand: another_command
another_command:
	echo "huh..."
bad_command:
	false
	echo "nope..."
